# Generated by Django 4.2.6 on 2023-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0002_journal_goal_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
