# Generated by Django 4.2.6 on 2023-10-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0003_journal_journal_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=15, null=True),
        ),
    ]
