# Generated by Django 4.2.6 on 2023-10-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0004_alter_journal_journal_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='journal',
            new_name='journal_title',
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], default='Red', max_length=15),
        ),
    ]
