# Generated by Django 4.2.6 on 2023-10-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0005_rename_journal_entries_journal_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='journal_title',
            new_name='journal',
        ),
    ]
