# Generated by Django 4.2.6 on 2023-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0006_rename_journal_title_entries_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
    ]
