# Generated by Django 4.2.6 on 2023-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0007_timer_remove_goal_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='progress_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
