# Generated by Django 4.2.6 on 2023-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goalify', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
